python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/1 \
	--output_node_name=hourglass_out_3 \
	--json_name=1
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/2 \
	--output_node_name=hourglass_out_3 \
	--json_name=2
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/3 \
	--output_node_name=hourglass_out_3 \
	--json_name=3
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/4 \
	--output_node_name=hourglass_out_3 \
	--json_name=4
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/5 \
	--output_node_name=hourglass_out_3 \
	--json_name=5
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/6 \
	--output_node_name=hourglass_out_3 \
	--json_name=6
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/7 \
	--output_node_name=hourglass_out_3 \
	--json_name=7
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/8 \
	--output_node_name=hourglass_out_3 \
	--json_name=8
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/9 \
	--output_node_name=hourglass_out_3 \
	--json_name=9
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/10 \
	--output_node_name=hourglass_out_3 \
	--json_name=10
python src/my_test.py --frozen_pb_path=../release/hourglass_model/model.pb \
	--img_path=/home/dingqianggang/yd/yxy_dataset/yxy_example_video_dataset/11 \
	--output_node_name=hourglass_out_3 \
	--json_name=11
